apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - uses: docker://python:latest
        name: Say hello
        run: lscpu
  A:
    steps:
      - uses: docker://python:latest
        name: Run
        run: lscpu
